local addonName, AGB = ...

-- Generated by tools/wowhead_stats_bulk_capture.py.
-- Reviewed production Stats data. Only exact captures are emitted.
AGB.GuideStatsData = {
    schemaVersion = 1,
    specs = {
        [62] = {
            sourceName = "Wowhead - Arcane Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/mage/arcane/stat-priority-pve-dps",
            variants = {
                {
                    label = "Spellslinger Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Sunfury Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Versatility",
                        "Critical Strike",
                        "Mastery",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [63] = {
            sourceName = "Wowhead - Fire Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/stat-priority-pve-dps",
            variants = {
                {
                    label = "Sunfury Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Versatility",
                        "Critical Strike",
                    },
                },
                {
                    label = "Frostfire Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Versatility",
                        "Critical Strike",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [64] = {
            sourceName = "Wowhead - Frost Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/mage/frost/stat-priority-pve-dps",
            variants = {
                {
                    label = "Frostfire Stat Priority",
                    priority = {
                        "Intellect",
                        "Mastery",
                        "Critical Strike",
                        "Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Spellslinger Stat Priority",
                    priority = {
                        "Intellect",
                        "Mastery",
                        "Critical Strike",
                        "Haste",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [65] = {
            sourceName = "Wowhead - Holy Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/paladin/holy/stat-priority-pve-healer",
            variants = {
                {
                    label = "Herald of the Sun Stat Priority",
                    priority = {
                        "Intellect",
                        "Mastery",
                        "Haste = Crit",
                        "Versatility",
                    },
                },
                {
                    label = "Lightsmith Stat Priority",
                    priority = {
                        "Intellect",
                        "Mastery",
                        "Haste = Crit",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [66] = {
            sourceName = "Wowhead - Protection Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/paladin/protection/stat-priority-pve-tank",
            variants = {
                {
                    label = "Survivability Stat Priority",
                    priority = {
                        "Strength",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "DPS Stat Priority",
                    priority = {
                        "Strength",
                        "Haste",
                        "Critical Strike",
                        "Mastery",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [70] = {
            sourceName = "Wowhead - Retribution Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/paladin/retribution/stat-priority-pve-dps",
            variants = {
                {
                    label = "Templar Stat Priority",
                    priority = {
                        "Strength",
                        "Mastery",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Herald of the Sun Stat Priority",
                    priority = {
                        "Strength",
                        "Mastery",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [71] = {
            sourceName = "Wowhead - Arms Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/arms/stat-priority-pve-dps",
            variants = {
                {
                    label = "Colossus Stat Priority",
                    priority = {
                        "Strength",
                        "Critical Strike",
                        "Haste",
                        "Mastery",
                        "Versatility",
                    },
                },
                {
                    label = "Slayer Stat Priority",
                    priority = {
                        "Strength",
                        "Critical Strike",
                        "Haste",
                        "Mastery",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [72] = {
            sourceName = "Wowhead - Fury Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/fury/stat-priority-pve-dps",
            variants = {
                {
                    label = "Mountain Thane Stat Priority",
                    priority = {
                        "Strength",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Slayer Stat Priority",
                    priority = {
                        "Strength",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [73] = {
            sourceName = "Wowhead - Protection Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/protection/stat-priority-pve-tank",
            variants = {
                {
                    label = "Survivability Stat Priority",
                    priority = {
                        "Strength",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                        "Mastery",
                    },
                },
                {
                    label = "DPS Stat Priority",
                    priority = {
                        "Strength",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                        "Mastery",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [102] = {
            sourceName = "Wowhead - Balance Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/druid/balance/stat-priority-pve-dps",
            variants = {
                {
                    label = "Keeper of the Grove Stat Priority",
                    priority = {
                        "Intellect",
                        "Mastery",
                        "Haste = Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Elune's Chosen Stat Priority",
                    priority = {
                        "Intellect",
                        "Mastery",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [103] = {
            sourceName = "Wowhead - Feral Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/druid/feral/stat-priority-pve-dps",
            variants = {
                {
                    label = "Druid of the Claw Stat Priority",
                    priority = {
                        "Agility",
                        "Mastery",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Wildstalker Stat Priority",
                    priority = {
                        "Agility",
                        "Mastery",
                        "Critical Strike",
                        "Haste",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [104] = {
            sourceName = "Wowhead - Guardian Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/druid/guardian/stat-priority-pve-tank",
            variants = {
                {
                    label = "Survivability Stat Priority",
                    priority = {
                        "Agility",
                        "Haste",
                        "Versatility",
                        "Critical Strike",
                        "Mastery",
                    },
                },
                {
                    label = "DPS Stat Priority",
                    priority = {
                        "Agility",
                        "Haste",
                        "Versatility",
                        "Critical Strike",
                        "Mastery",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [105] = {
            sourceName = "Wowhead - Restoration Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/druid/restoration/stat-priority-pve-healer",
            variants = {
                {
                    label = "Keeper of the Grove Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Versatility",
                        "Critical Strike",
                    },
                },
                {
                    label = "Wildstalker Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Versatility",
                        "Critical Strike",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [250] = {
            sourceName = "Wowhead - Blood Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/death-knight/blood/stat-priority-pve-tank",
            variants = {
                {
                    label = "San'layn Stat Priority",
                    priority = {
                        "Strength",
                        "Haste",
                        "Mastery / Critical Strike / Versatility",
                    },
                },
                {
                    label = "Deathbringer Stat Priority",
                    priority = {
                        "Strength",
                        "Critical Strike",
                        "Mastery / Versatility",
                        "Haste",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [251] = {
            sourceName = "Wowhead - Frost Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/stat-priority-pve-dps",
            variants = {
                {
                    label = "Deathbringer Stat Priority",
                    priority = {
                        "Strength",
                        "Critical Strike",
                        "Mastery",
                        "Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Rider of the Apocalypse Stat Priority",
                    priority = {
                        "Strength",
                        "Critical Strike",
                        "Mastery",
                        "Haste",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [252] = {
            sourceName = "Wowhead - Unholy Stat Priority - Midnight",
            sourceUpdated = "2026-08-17",
            sourceURL = "https://www.wowhead.com/guide/classes/death-knight/unholy/stat-priority-pve-dps",
            variants = {
                {
                    label = "San'layn Stat Priority",
                    priority = {
                        "Strength",
                        "Crit",
                        "Mastery",
                        "Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Rider of the Apocalypse Stat Priority",
                    priority = {
                        "Strength",
                        "Crit",
                        "Mastery",
                        "Haste",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [253] = {
            sourceName = "Wowhead - Beast Mastery Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/stat-priority-pve-dps",
            variants = {
                {
                    label = "Pack Leader Stat Priority — All Situations",
                    priority = {
                        "Weapon Damage",
                        "Agility",
                        "Mastery",
                        "Critical Strike",
                        "Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Dark Ranger Stat Priority — Single-Target",
                    priority = {
                        "Weapon Damage",
                        "Agility",
                        "Critical Strike",
                        "Mastery",
                        "Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Dark Ranger Stat Priority — AoE",
                    priority = {
                        "Weapon Damage",
                        "Agility",
                        "Mastery",
                        "Critical Strike",
                        "Haste",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [254] = {
            sourceName = "Wowhead - Marksmanship Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/hunter/marksmanship/stat-priority-pve-dps",
            variants = {
                {
                    label = "Sentinel Stat Priority",
                    priority = {
                        "Agility",
                        "Critical Strike",
                        "Mastery",
                        "Versatility",
                        "Haste",
                    },
                },
                {
                    label = "Dark Ranger Stat Priority",
                    priority = {
                        "Agility",
                        "Critical Strike",
                        "Mastery",
                        "Versatility",
                        "Haste",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [255] = {
            sourceName = "Wowhead - Survival Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/hunter/survival/stat-priority-pve-dps",
            variants = {
                {
                    label = "Pack Leader Stat Priority",
                    priority = {
                        "Agility",
                        "Mastery",
                        "Critical Strike and Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Sentinel Stat Priority",
                    priority = {
                        "Agility",
                        "Mastery",
                        "Critical Strike",
                        "Haste",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [256] = {
            sourceName = "Wowhead - Discipline Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/priest/discipline/stat-priority-pve-healer",
            variants = {
                {
                    label = "Oracle Stat Priority — Raid",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Voidweaver Stat Priority — Raid",
                    priority = {
                        "Haste",
                        "Intellect",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Oracle Stat Priority — Dungeons",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Voidweaver Stat Priority — Dungeons",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [257] = {
            sourceName = "Wowhead - Holy Stat Priority - Midnight",
            sourceUpdated = "2026-09-03",
            sourceURL = "https://www.wowhead.com/guide/classes/priest/holy/stat-priority-pve-healer",
            variants = {
                {
                    label = "Archon Stat Priority — Raid",
                    priority = {
                        "Intellect",
                        "Crit",
                        "Versatility = Mastery",
                        "Haste",
                    },
                },
                {
                    label = "Oracle Stat Priority — Raid",
                    priority = {
                        "Intellect",
                        "Haste to comfort (~20%)",
                        "Crit",
                        "Versatility = Mastery",
                        "Haste",
                    },
                },
                {
                    label = "Archon Stat Priority — Dungeons/Mythic+",
                    priority = {
                        "Intellect",
                        "Versatility",
                        "Critical Strike",
                        "Haste",
                        "Mastery",
                    },
                },
                {
                    label = "Oracle Stat Priority — Dungeons/Mythic+",
                    priority = {
                        "Intellect",
                        "Haste to comfort (~20%)",
                        "Versatility",
                        "Critical Strike",
                        "Haste",
                        "Mastery",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [258] = {
            sourceName = "Wowhead - Shadow Stat Priority - Midnight",
            sourceUpdated = "2026-08-31",
            sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/stat-priority-pve-dps",
            variants = {
                {
                    label = "Archon Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Voidweaver Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [259] = {
            sourceName = "Wowhead - Assassination Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/rogue/assassination/stat-priority-pve-dps",
            variants = {
                {
                    label = "Fatebound Stat Priority",
                    priority = {
                        "Agility",
                        "Critical Strike",
                        "Haste",
                        "Mastery",
                        "Versatility",
                    },
                },
                {
                    label = "Deathstalker Stat Priority",
                    priority = {
                        "Agility",
                        "Critical Strike",
                        "Haste",
                        "Mastery",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [260] = {
            sourceName = "Wowhead - Outlaw Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/rogue/outlaw/stat-priority-pve-dps",
            variants = {
                {
                    label = "Trickster Stat Priority",
                    priority = {
                        "Agility",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                        "Mastery",
                    },
                },
                {
                    label = "Fatebound Stat Priority",
                    priority = {
                        "Agility",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                        "Mastery",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [261] = {
            sourceName = "Wowhead - Subtlety Stat Priority - Midnight",
            sourceUpdated = "2026-08-19",
            sourceURL = "https://www.wowhead.com/guide/classes/rogue/subtlety/stat-priority-pve-dps",
            variants = {
                {
                    label = "Deathstalker Stat Priority",
                    priority = {
                        "Agility",
                        "Mastery",
                        "Haste (~700 Haste)",
                        "Versatility",
                        "Critical Strike",
                    },
                },
                {
                    label = "Trickster Stat Priority",
                    priority = {
                        "Agility",
                        "Mastery",
                        "Haste (~700 Haste)",
                        "Versatility",
                        "Critical Strike",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [262] = {
            sourceName = "Wowhead - Elemental Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/shaman/elemental/stat-priority-pve-dps",
            variants = {
                {
                    label = "Farseer Stat Priority",
                    priority = {
                        "Mastery to 1200 rating",
                        "Haste/Crit",
                        "Versatility",
                        "Intellect",
                    },
                },
                {
                    label = "Stormbringer Stat Priority",
                    priority = {
                        "Mastery to 1200 rating",
                        "Haste/Crit",
                        "Versatility",
                        "Intellect",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Both current Elemental Hero trees share the same reviewed ordering; exact upgrades remain gear/build/content dependent.",
        },
        [265] = {
            sourceName = "Wowhead - Affliction Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warlock/affliction/stat-priority-pve-dps",
            variants = {
                {
                    label = "Hellcaller Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                        "Mastery",
                    },
                },
                {
                    label = "Soul Harvester Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                        "Mastery",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [266] = {
            sourceName = "Wowhead - Demonology Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warlock/demonology/stat-priority-pve-dps",
            variants = {
                {
                    label = "Diabolist Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste=Critical Strike",
                        "Mastery",
                        "Versatility",
                    },
                },
                {
                    label = "Soul Harvester Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste=Critical Strike",
                        "Mastery",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [267] = {
            sourceName = "Wowhead - Destruction Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warlock/destruction/stat-priority-pve-dps",
            variants = {
                {
                    label = "Diabolist Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery>=Critical Strike",
                        "Versatility",
                    },
                },
                {
                    label = "Hellcaller Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery>=Critical Strike",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [268] = {
            sourceName = "Wowhead - Brewmaster Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/stat-priority-pve-tank",
            variants = {
                {
                    label = "Shado-Pan Defensive Priority",
                    priority = {
                        "Item Level / Agility / Armor / Stamina",
                        "Versatility = Critical Strike = Mastery",
                        "Haste",
                    },
                },
                {
                    label = "Master of Harmony Defensive Priority",
                    priority = {
                        "Item Level / Agility / Armor / Stamina",
                        "Versatility = Critical Strike = Mastery",
                        "Haste",
                    },
                },
                {
                    label = "Shado-Pan Offensive Priority",
                    priority = {
                        "Item Level / Agility",
                        "Critical Strike",
                        "Versatility = Mastery",
                        "Haste",
                    },
                },
                {
                    label = "Master of Harmony Offensive Priority",
                    priority = {
                        "Item Level / Agility",
                        "Critical Strike",
                        "Versatility = Mastery",
                        "Haste",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [269] = {
            sourceName = "Wowhead - Windwalker Stat Priority - Midnight",
            sourceUpdated = "2026-09-04",
            sourceURL = "https://www.wowhead.com/guide/classes/monk/windwalker/stat-priority-pve-dps",
            variants = {
                {
                    label = "Shado-pan Stat Priority",
                    priority = {
                        "Agility",
                        "Haste = Critical Strike = Mastery",
                        "Versatility",
                    },
                },
                {
                    label = "Conduit of the Celestials Stat Priority",
                    priority = {
                        "Agility",
                        "Haste = Critical Strike = Mastery",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [270] = {
            sourceName = "Wowhead - Mistweaver Stat Priority - Midnight",
            sourceUpdated = "2026-09-05",
            sourceURL = "https://www.wowhead.com/guide/classes/monk/mistweaver/stat-priority-pve-healer",
            variants = {
                {
                    label = "Raid Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Critical Strike",
                        "Versatility",
                        "Mastery",
                    },
                },
                {
                    label = "Mythic+ Stat Priority",
                    priority = {
                        "Intellect",
                        "Haste",
                        "Mastery",
                        "Critical Strike",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [1467] = {
            sourceName = "Wowhead - Devastation Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/stat-priority-pve-dps",
            variants = {
                {
                    label = "Flameshaper Stat Priority",
                    priority = {
                        "Intellect",
                        "Critical Strike",
                        "Mastery",
                        "Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Scalecommander Stat Priority",
                    priority = {
                        "Intellect",
                        "Critical Strike",
                        "Mastery",
                        "Haste",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [1468] = {
            sourceName = "Wowhead - Preservation Stat Priority - Midnight",
            sourceUpdated = "2026-08-31",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/preservation/stat-priority-pve-healer",
            variants = {
                {
                    label = "Preservation Raid Stat Priority",
                    priority = {
                        "Intellect",
                        "Crit",
                        "Mastery",
                        "Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Preservation Mythic+ Stat Priority",
                    priority = {
                        "Intellect",
                        "Crit",
                        "Haste",
                        "Mastery",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
        [1473] = {
            sourceName = "Wowhead - Augmentation Stat Priority - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/augmentation/stat-priority-pve-dps",
            variants = {
                {
                    label = "Chronowarden Stat Priority",
                    priority = {
                        "Intellect",
                        "Mastery",
                        "Critical Strike",
                        "Haste",
                        "Versatility",
                    },
                },
                {
                    label = "Scalecommander Stat Priority",
                    priority = {
                        "Intellect",
                        "Mastery",
                        "Critical Strike",
                        "Haste",
                        "Versatility",
                    },
                },
            },
            note = "Source-listed general stat priorities captured from Wowhead. Keep source-listed variants separate; exact upgrades remain gear/build/content dependent.",
        },
    },
}

local function UpsertStatsSource(data, stats)
    data.sources = data.sources or {}
    for _, source in ipairs(data.sources) do
        if source.label == "Stats" then
            source.updated = stats.sourceUpdated or source.updated
            source.url = stats.sourceURL or source.url
            return
        end
    end
    table.insert(data.sources, { label = "Stats", updated = stats.sourceUpdated or "unknown", url = stats.sourceURL })
end

for specID, stats in pairs((AGB.GuideStatsData and AGB.GuideStatsData.specs) or {}) do
    local meta = AGB.SpecIndex and AGB.SpecIndex[specID]
    local data = meta and AGB.Data and AGB.Data[meta.classFile] and AGB.Data[meta.classFile][specID]
    if data and stats and stats.sourceURL and stats.variants and #stats.variants > 0 then
        data.stats = stats
        UpsertStatsSource(data, stats)
    end
end