local addonName, AGB = ...

-- Generated by tools/wowhead_consumables_bulk_capture.py.
-- Only exact specialization captures are bundled; partial captures stay diagnostic-only.
AGB.GuideConsumablesData = {
    schemaVersion = 1,
    generatedAt = "2026-09-27",
    specs = {
        [62] = {
            sourceName = "Wowhead - Arcane Mage Enchants & Consumables - Midnight",
            sourceUpdated = "2026-09-05",
            sourceURL = "https://www.wowhead.com/guide/classes/mage/arcane/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [63] = {
            sourceName = "Wowhead - Fire Mage Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/mage/fire/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
                {
                    type = "Food",
                    id = 242272,
                    name = "Quel'dorei Medley",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [64] = {
            sourceName = "Wowhead - Frost Mage Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/mage/frost/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
                {
                    type = "Food",
                    id = 242274,
                    name = "Champion's Bento",
                },
                {
                    type = "Tea",
                    id = 242298,
                    name = "Argentleaf Tea",
                },
                {
                    type = "Tea",
                    id = 242299,
                    name = "Sanguithorn Tea",
                },
                {
                    type = "Tea",
                    id = 242301,
                    name = "Azeroot Tea",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [65] = {
            sourceName = "Wowhead - Holy Paladin Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-28",
            sourceURL = "https://www.wowhead.com/guide/classes/paladin/holy/enchants-gems-pve-healer",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Stats Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Mana Potion",
                    id = 241300,
                    name = "Lightfused Mana Potion",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                    context = "as Herald",
                },
                {
                    type = "Weapon Buff",
                    spellID = 433568,
                    name = "Rite of Sanctification",
                    context = "as Lightsmith",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 275264,
                    name = "Amani Cornucopia",
                },
                {
                    type = "Food",
                    id = 242299,
                    name = "Sanguithorn Tea",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [66] = {
            sourceName = "Wowhead - Protection Paladin Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/paladin/protection/enchants-gems-pve-tank",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241292,
                    name = "Draught of Rampant Abandon",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [70] = {
            sourceName = "Wowhead - Retribution Paladin Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-25",
            sourceURL = "https://www.wowhead.com/guide/classes/paladin/retribution/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271883,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [71] = {
            sourceName = "Wowhead - Arms Warrior Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-26",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/arms/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 242273,
                    name = "Blooming Feast",
                },
                {
                    type = "Food",
                    id = 242274,
                    name = "Champion's Bento",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [72] = {
            sourceName = "Wowhead - Fury Warrior Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-26",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/fury/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 242273,
                    name = "Blooming Feast",
                },
                {
                    type = "Food",
                    id = 242274,
                    name = "Champion's Bento",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [73] = {
            sourceName = "Wowhead - Protection Warrior Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warrior/protection/enchants-gems-pve-tank",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241292,
                    name = "Draught of Rampant Abandon",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [102] = {
            sourceName = "Wowhead - Balance Druid Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-25",
            sourceURL = "https://www.wowhead.com/guide/classes/druid/balance/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243733,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255847,
                    name = "Impossibly Royal Roast",
                },
                {
                    type = "Food",
                    id = 242274,
                    name = "Champion's Bento",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [103] = {
            sourceName = "Wowhead - Feral Druid Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/druid/feral/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                    context = "(best)",
                },
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                    context = "(alternative)",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff (Main Hand)",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Weapon Buff (Off Hand)",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                    context = "(feast)",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                },
                {
                    type = "Food",
                    id = 242299,
                    name = "Sanguithorn Tea",
                    context = "(Stacks with other food)",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [104] = {
            sourceName = "Wowhead - Guardian Druid Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/druid/guardian/enchants-gems-pve-tank",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241292,
                    name = "Draught of Rampant Abandon",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [105] = {
            sourceName = "Wowhead - Restoration Druid Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/druid/restoration/enchants-gems-pve-healer",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                    context = "(Preferred)",
                },
                {
                    type = "Combat Potion",
                    id = 241300,
                    name = "Lightfused Mana Potion",
                    context = "(Situational)",
                },
                {
                    type = "Health Potion",
                    id = 241304,
                    name = "Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [250] = {
            sourceName = "Wowhead - Blood Death Knight Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/death-knight/blood/enchants-gems-pve-tank",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 242273,
                    name = "Blooming Feast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [251] = {
            sourceName = "Wowhead - Frost Death Knight Enchants & Consumables - Midnight",
            sourceUpdated = "2026-09-05",
            sourceURL = "https://www.wowhead.com/guide/classes/death-knight/frost/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 241304,
                    name = "Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [252] = {
            sourceName = "Wowhead - Unholy Death Knight Enchants & Consumables - Midnight",
            sourceUpdated = "2026-09-10",
            sourceURL = "https://www.wowhead.com/guide/classes/death-knight/unholy/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 241304,
                    name = "Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Weapon Buff",
                    id = 237371,
                    name = "Refulgent Whetstone",
                },
                {
                    type = "Weapon Buff",
                    id = 237369,
                    name = "Refulgent Weightstone",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [253] = {
            sourceName = "Wowhead - Beast Mastery Hunter Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-24",
            sourceURL = "https://www.wowhead.com/guide/classes/hunter/beast-mastery/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                    context = "(Raid)",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                    context = "(Near-BiS gear with low Versatility)",
                },
                {
                    type = "Combat Potion",
                    id = 271887,
                    name = "Liquid Luster",
                    context = "(Mythic+)",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                    context = "(feast)",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                    context = "(personal)",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [254] = {
            sourceName = "Wowhead - Marksmanship Hunter Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-24",
            sourceURL = "https://www.wowhead.com/guide/classes/hunter/marksmanship/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Feast",
                    id = 255846,
                    name = "Harandar Celebration",
                },
                {
                    type = "Feast",
                    id = 255845,
                    name = "Silvermoon Parade",
                },
                {
                    type = "Personal Food",
                    id = 242747,
                    name = "Hearty Royal Roast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [255] = {
            sourceName = "Wowhead - Survival Hunter Enchants & Consumables - Midnight",
            sourceUpdated = "2026-09-08",
            sourceURL = "https://www.wowhead.com/guide/classes/hunter/survival/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 245933,
                    name = "Fleeting Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Food",
                    id = 275265,
                    name = "Loa's Gathering",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [256] = {
            sourceName = "Wowhead - Discipline Priest Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/priest/discipline/enchants-gems-pve-healer",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [257] = {
            sourceName = "Wowhead - Holy Priest Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/priest/holy/enchants-gems-pve-healer",
            items = {
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [258] = {
            sourceName = "Wowhead - Shadow Priest Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-13",
            sourceURL = "https://www.wowhead.com/guide/classes/priest/shadow/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 242273,
                    name = "Blooming Feast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [259] = {
            sourceName = "Wowhead - Assassination Rogue Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-29",
            sourceURL = "https://www.wowhead.com/guide/classes/rogue/assassination/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 271887,
                    name = "Liquid Luster",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [260] = {
            sourceName = "Wowhead - Outlaw Rogue Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/rogue/outlaw/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241309,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [261] = {
            sourceName = "Wowhead - Subtlety Rogue Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-24",
            sourceURL = "https://www.wowhead.com/guide/classes/rogue/subtlety/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                    context = "(best)",
                },
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                    context = "(alternative)",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                    context = "(default)",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                    context = "(if you get Mastery)",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff (Main Hand)",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Weapon Buff (Off Hand)",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                    context = "(feast)",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                    context = "(personal)",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [265] = {
            sourceName = "Wowhead - Affliction Warlock Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warlock/affliction/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [266] = {
            sourceName = "Wowhead - Demonology Warlock Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warlock/demonology/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [267] = {
            sourceName = "Wowhead - Destruction Warlock Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/warlock/destruction/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Combat Potion",
                    id = 241308,
                    name = "Light's Potential",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [268] = {
            sourceName = "Wowhead - Brewmaster Monk Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-25",
            sourceURL = "https://www.wowhead.com/guide/classes/monk/brewmaster/enchants-gems-pve-tank",
            items = {
                {
                    type = "Flask",
                    id = 241320,
                    name = "Flask of Thalassian Resistance",
                },
                {
                    type = "Combat Potion",
                    id = 271887,
                    name = "Liquid Luster",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Health Potion",
                    id = 5512,
                    name = "Healthstone",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                    context = "(Hearty)",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                    context = "(Hearty)",
                },
                {
                    type = "Food",
                    id = 242275,
                    name = "Royal Roast",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [269] = {
            sourceName = "Wowhead - Windwalker Monk Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-25",
            sourceURL = "https://www.wowhead.com/guide/classes/monk/windwalker/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271883,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
                {
                    type = "Food",
                    id = 255845,
                    name = "Silvermoon Parade",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [270] = {
            sourceName = "Wowhead - Mistweaver Monk Enchants & Consumables - Midnight",
            sourceUpdated = "2026-09-12",
            sourceURL = "https://www.wowhead.com/guide/classes/monk/mistweaver/enchants-gems-pve-healer",
            items = {
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Invisibility Potion",
                    id = 241302,
                    name = "Void-Shrouded Tincture",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Feast",
                    id = 266996,
                    name = "Hearty Harandar Celebration",
                },
                {
                    type = "Personal Food",
                    id = 242747,
                    name = "Hearty Royal Roast",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [1467] = {
            sourceName = "Wowhead - Devastation Evoker Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/devastation/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
                {
                    type = "Food",
                    id = 242272,
                    name = "Quel'dorei Medley",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [1468] = {
            sourceName = "Wowhead - Preservation Evoker Enchants & Consumables - Midnight",
            sourceUpdated = "2026-09-10",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/preservation/enchants-gems-pve-healer",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Flask",
                    id = 241326,
                    name = "Flask of the Shattered Sun",
                },
                {
                    type = "Flask",
                    id = 241324,
                    name = "Flask of the Blood Knights",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 241304,
                    name = "Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 255846,
                    name = "Harandar Celebration",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
        [1473] = {
            sourceName = "Wowhead - Augmentation Evoker Enchants & Consumables - Midnight",
            sourceUpdated = "2026-08-12",
            sourceURL = "https://www.wowhead.com/guide/classes/evoker/augmentation/enchants-gems-pve-dps",
            items = {
                {
                    type = "Flask",
                    id = 241322,
                    name = "Flask of the Magisters",
                },
                {
                    type = "Combat Potion",
                    id = 241288,
                    name = "Potion of Recklessness",
                },
                {
                    type = "Health Potion",
                    id = 271884,
                    name = "Concentrated Silvermoon Health Potion",
                },
                {
                    type = "Weapon Buff",
                    id = 243734,
                    name = "Thalassian Phoenix Oil",
                },
                {
                    type = "Augment Rune",
                    id = 259085,
                    name = "Void-Touched Augment Rune",
                },
                {
                    type = "Food",
                    id = 266985,
                    name = "Hearty Silvermoon Parade",
                    context = "(feast)",
                },
                {
                    type = "Food",
                    id = 242747,
                    name = "Hearty Royal Roast",
                    context = "(personal)",
                },
            },
            note = "Source-listed consumable recommendations captured from Wowhead. Multiple rows with the same type represent source-listed alternatives or situational choices; hover entries for the normal WoW tooltip.",
        },
    },
}

local function UpsertConsumablesSource(data, consumables)
    data.sources = data.sources or {}
    for _, source in ipairs(data.sources) do
        if source.label == "Consumables / Enchants / Gems" or source.label == "Consumables" then
            source.label = "Consumables / Enchants / Gems"
            source.updated = consumables.sourceUpdated or source.updated
            source.url = consumables.sourceURL or source.url
            return
        end
    end
    table.insert(data.sources, { label = "Consumables / Enchants / Gems", updated = consumables.sourceUpdated or "unknown", url = consumables.sourceURL })
end

for specID, consumables in pairs((AGB.GuideConsumablesData and AGB.GuideConsumablesData.specs) or {}) do
    local meta = AGB.SpecIndex and AGB.SpecIndex[specID]
    local data = meta and AGB.Data and AGB.Data[meta.classFile] and AGB.Data[meta.classFile][specID]
    if data and consumables and consumables.sourceURL then
        data.consumables = consumables
        UpsertConsumablesSource(data, consumables)
    end
end