local addonName, AGB = ...

-- Generated by Azeroth Guidebook Companion after an automatic refresh run.
-- The distributed package starts with no local refresh history.
AGB.SourceRefreshState = {
    schemaVersion = 2,
    generatedAt = nil,
    lastRun = nil,
    history = {},
    entries = {},
}